[package]
name = "capn"
version = "0.1.0"
authors = ["comex <comexk@gmail.com>"]
build = "build.rs"


[dependencies]
capnp = "0.9.1"
memmap = "0.7.0"

[build-dependencies]
capnpc = "0.9"

[profile.release]
debug = true
